name: "Matrix"
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16,18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Get Code"
        uses: actions/checkout@v4
      - name: "Setup Nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: "Install Dependencies"
        run: npm ci
      - name: "Build the project"
        run: npm run build
