name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of the deploying artifact"
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: This variable shows output of the workflow
        value: ${{ jobs.deploy.outputs.jobOutput }}
jobs:
  deploy:
    outputs:
      jobOutput: ${{steps.resultStep.outputs.result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: "List files"
        run: ls
      - name: "Output information"
        run: |
          echo "Deploying"
          echo "${{ toJson(github) }}"
      - name: "Set Result output"
        id: resultStep
        run: echo "result=success" >> $GITHUB_OUTPUT